[build]
command = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn HMS.wsgi"
publish = "staticfiles"

[build.environment]
DJANGO_SECRET_KEY = "your_secret_key_here"
DATABASE_URL = "your_database_url_here"
