# Generated by Django 5.1 on 2024-09-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.')], max_length=4)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_first_name', models.CharField(max_length=50)),
                ('birth_middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender_identity', models.CharField(choices=[('male', 'Identifies as Male'), ('female', 'Identifies as Female')], max_length=10)),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unknown', 'Unknown')], max_length=7)),
                ('sexual_orientation', models.CharField(choices=[('straight', 'Straight'), ('lesbian', 'Lesbian'), ('bisexual', 'Bisexual')], max_length=10)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=7)),
                ('address', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='India', max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
